services:
  kong:
    image: ghcr.io/idp-one-calendar-2026/infra-config/kong:latest
    ports:
      - "8000:8000"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yaml"
    networks:
      - auth-network
    deploy:
      replicas: 1

  auth-service:
    image: ghcr.io/idp-one-calendar-2026/auth-service:latest
    environment:
      DATABASE_URL: "file:/data/auth.db"
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      VITE_UI_URL: ${VITE_UI_URL}
      VITE_API_URL: ${VITE_API_URL}
      BETTER_AUTH_TRUSTED_ORIGINS: ${BETTER_AUTH_TRUSTED_ORIGINS}
    volumes:
      - auth_data:/data
    networks:
      - auth-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
  ui-service:
    image: ghcr.io/idp-one-calendar-2026/ui:latest
    environment:
      VITE_BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      VITE_API_URL: ${VITE_API_URL}
    networks:
      - ui-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any


volumes:
  auth_data:

networks:
  ui-network:
    driver: overlay
  auth-network:
    driver: overlay